#!/bin/sh

DOCKER_ROOT="$HOME/docker"
DOCKER_ENV="$DOCKER_ROOT/.env"

mkdir -pv $DOCKER_ROOT
touch $DOCKER_ENV

mkdir -pv $DOCKER_ROOT/shared
mkdir -pv $DOCKER_ROOT/portainer
mkdir -pv $DOCKER_ROOT/organizr
mkdir -pv $DOCKER_ROOT/transmission
mkdir -pv $DOCKER_ROOT/radarr
mkdir -pv $DOCKER_ROOT/sonarr
mkdir -pv $DOCKER_ROOT/plexms
mkdir -pv $DOCKER_ROOT/plex_tmp

mkdir -pv $HOME/downloads
mkdir -pv $HOME/watch
mkdir -pv $HOME/media/movies
mkdir -pv $HOME/media/tvshows

echo "PUID=`id -u $USER`" > $DOCKER_ENV
echo "PGID=`getent group sudo | awk -F: '{printf $3}'`" >> $DOCKER_ENV
echo "TZ=`cat /etc/timezone`" >> $DOCKER_ENV
echo "USERDIR=`echo $HOME`" >> $DOCKER_ENV
read -p 'Plex server claim (https://www.plex.tv/claim/): ' plex_claim
echo "PLEX_CLAIM=$plex_claim" >> $DOCKER_ENV
echo "SERVER_ADDR=`hostname -I | awk '{print $1}'`" >> $DOCKER_ENV
echo "Created .env file:"
echo "`cat $DOCKER_ENV`"
echo ""
echo "Done!"
