#!/bin/sh

DOCKER_HOME="$HOME/docker"
DOCKER_ENV="$DOCKER_HOME/.env"

mkdir -pv $DOCKER_HOME
touch $DOCKER_ENV

echo "PUID=`id -u $USER`" > $DOCKER_ENV
echo "PGID=`getent group sudo | awk -F: '{printf $3}'`" >> $DOCKER_ENV
echo "TZ=`cat /etc/timezone`" >> $DOCKER_ENV
echo "USERDIR=`echo $HOME`" >> $DOCKER_ENV
read -p 'Plex server claim (https://www.plex.tv/claim/): ' plex_claim
echo "PLEX_CLAIM=$plex_claim" >> $DOCKER_ENV
echo "SERVER_ADDR=`hostname -I | awk '{print $1}'`" >> $DOCKER_ENV
echo "Created .env file:"
echo "`cat $DOCKER_ENV`"

mkdir -pv $DOCKER_HOME/shared
mkdir -pv $DOCKER_HOME/portainer
mkdir -pv $DOCKER_HOME/organizr
mkdir -pv $DOCKER_HOME/transmission
mkdir -pv $DOCKER_HOME/radarr
mkdir -pv $DOCKER_HOME/sonarr
mkdir -pv $DOCKER_HOME/plexms
mkdir -pv $DOCKER_HOME/plex_tmp

mkdir -pv $HOME/downloads
mkdir -pv $HOME/watch
mkdir -pv $HOME/media/movies
mkdir -pv $HOME/media/tvshows
