#!/bin/sh

mkdir -pv $HOME/docker
DOCKER_ENV="$HOME/docker/.env"
touch $DOCKER_ENV
echo "PUID=`id -u $USER`" > $DOCKER_ENV
echo "PGID=`getent group docker | awk -F: '{printf $3}'`" >> $DOCKER_ENV
echo "TZ=`cat /etc/timezone`" >> $DOCKER_ENV
echo "USERDIR=`echo $HOME`" >> $DOCKER_ENV
read -p 'Plex server claim (https://www.plex.tv/claim/): ' plex_claim
echo "PLEX_CLAIM=$plex_claim" >> $DOCKER_ENV
echo "SERVER_ADDR=`hostname -I | awk '{print $1}'`" >> $DOCKER_ENV
echo "Created .env file:"
echo "`cat $DOCKER_ENV`"

mkdir -pv ~/docker/shared
mkdir -pv ~/docker/portainer
mkdir -pv ~/docker/organizr
mkdir -pv ~/docker/transmission
mkdir -pv ~/docker/radarr
mkdir -pv ~/docker/sonarr
mkdir -pv ~/docker/plexms
mkdir -pv ~/docker/plex_tmp

mkdir -pv ~/downloads
mkdir -pv ~/watch
mkdir -pv ~/media/movies
mkdir -pv ~/media/tvshows
